apiVersion: incapsula.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: imperva-creds
      namespace: upbound-system
      key: credentials
