//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociation) DeepCopyInto(out *PolicyAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociation.
func (in *PolicyAssociation) DeepCopy() *PolicyAssociation {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationInitParameters) DeepCopyInto(out *PolicyAssociationInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AvailablePolicyIds != nil {
		in, out := &in.AvailablePolicyIds, &out.AvailablePolicyIds
		*out = new(string)
		**out = **in
	}
	if in.DefaultNonMandatoryPolicyIds != nil {
		in, out := &in.DefaultNonMandatoryPolicyIds, &out.DefaultNonMandatoryPolicyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultNonMandatoryPolicyIdsRefs != nil {
		in, out := &in.DefaultNonMandatoryPolicyIdsRefs, &out.DefaultNonMandatoryPolicyIdsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultNonMandatoryPolicyIdsSelector != nil {
		in, out := &in.DefaultNonMandatoryPolicyIdsSelector, &out.DefaultNonMandatoryPolicyIdsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultWafPolicyID != nil {
		in, out := &in.DefaultWafPolicyID, &out.DefaultWafPolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationInitParameters.
func (in *PolicyAssociationInitParameters) DeepCopy() *PolicyAssociationInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationList) DeepCopyInto(out *PolicyAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationList.
func (in *PolicyAssociationList) DeepCopy() *PolicyAssociationList {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationObservation) DeepCopyInto(out *PolicyAssociationObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AvailablePolicyIds != nil {
		in, out := &in.AvailablePolicyIds, &out.AvailablePolicyIds
		*out = new(string)
		**out = **in
	}
	if in.DefaultNonMandatoryPolicyIds != nil {
		in, out := &in.DefaultNonMandatoryPolicyIds, &out.DefaultNonMandatoryPolicyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultWafPolicyID != nil {
		in, out := &in.DefaultWafPolicyID, &out.DefaultWafPolicyID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationObservation.
func (in *PolicyAssociationObservation) DeepCopy() *PolicyAssociationObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationParameters) DeepCopyInto(out *PolicyAssociationParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.AvailablePolicyIds != nil {
		in, out := &in.AvailablePolicyIds, &out.AvailablePolicyIds
		*out = new(string)
		**out = **in
	}
	if in.DefaultNonMandatoryPolicyIds != nil {
		in, out := &in.DefaultNonMandatoryPolicyIds, &out.DefaultNonMandatoryPolicyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultNonMandatoryPolicyIdsRefs != nil {
		in, out := &in.DefaultNonMandatoryPolicyIdsRefs, &out.DefaultNonMandatoryPolicyIdsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultNonMandatoryPolicyIdsSelector != nil {
		in, out := &in.DefaultNonMandatoryPolicyIdsSelector, &out.DefaultNonMandatoryPolicyIdsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultWafPolicyID != nil {
		in, out := &in.DefaultWafPolicyID, &out.DefaultWafPolicyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationParameters.
func (in *PolicyAssociationParameters) DeepCopy() *PolicyAssociationParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationSpec) DeepCopyInto(out *PolicyAssociationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationSpec.
func (in *PolicyAssociationSpec) DeepCopy() *PolicyAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssociationStatus) DeepCopyInto(out *PolicyAssociationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssociationStatus.
func (in *PolicyAssociationStatus) DeepCopy() *PolicyAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyAssociationStatus)
	in.DeepCopyInto(out)
	return out
}
