/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/kernel-kun/provider-incapsula/apis/policy/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PolicyAssociation.
func (mg *PolicyAssociation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.DefaultNonMandatoryPolicyIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.DefaultNonMandatoryPolicyIdsRefs,
		Selector:      mg.Spec.ForProvider.DefaultNonMandatoryPolicyIdsSelector,
		To: reference.To{
			List:    &v1alpha1.PolicyList{},
			Managed: &v1alpha1.Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DefaultNonMandatoryPolicyIds")
	}
	mg.Spec.ForProvider.DefaultNonMandatoryPolicyIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.DefaultNonMandatoryPolicyIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.DefaultNonMandatoryPolicyIds),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.DefaultNonMandatoryPolicyIdsRefs,
		Selector:      mg.Spec.InitProvider.DefaultNonMandatoryPolicyIdsSelector,
		To: reference.To{
			List:    &v1alpha1.PolicyList{},
			Managed: &v1alpha1.Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DefaultNonMandatoryPolicyIds")
	}
	mg.Spec.InitProvider.DefaultNonMandatoryPolicyIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.DefaultNonMandatoryPolicyIdsRefs = mrsp.ResolvedReferences

	return nil
}
