/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/kernel-kun/provider-incapsula/apis/site/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AssetAssociation.
func (mg *AssetAssociation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AssetID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AssetIDRef,
		Selector:     mg.Spec.ForProvider.AssetIDSelector,
		To: reference.To{
			List:    &v1alpha1.SiteList{},
			Managed: &v1alpha1.Site{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AssetID")
	}
	mg.Spec.ForProvider.AssetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AssetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PolicyID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PolicyIDRef,
		Selector:     mg.Spec.ForProvider.PolicyIDSelector,
		To: reference.To{
			List:    &PolicyList{},
			Managed: &Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PolicyID")
	}
	mg.Spec.ForProvider.PolicyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PolicyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AssetID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AssetIDRef,
		Selector:     mg.Spec.InitProvider.AssetIDSelector,
		To: reference.To{
			List:    &v1alpha1.SiteList{},
			Managed: &v1alpha1.Site{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AssetID")
	}
	mg.Spec.InitProvider.AssetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AssetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PolicyID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.PolicyIDRef,
		Selector:     mg.Spec.InitProvider.PolicyIDSelector,
		To: reference.To{
			List:    &PolicyList{},
			Managed: &Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PolicyID")
	}
	mg.Spec.InitProvider.PolicyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PolicyIDRef = rsp.ResolvedReference

	return nil
}
